# SearXNG settings

use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG"

search:
  safe_search: 0
  formats:
    - json

server:
  secret_key: "dummy"
  port: 55510
  limiter: false
  image_proxy: false

ui:
  static_use_hash: true

enabled_plugins:
  - 'Hash plugin'
  - 'Self Informations'
  - 'Tracker URL remover'

engines:

  - name: ahmia
    disabled: true
    inactive: true

  - name: torch
    disabled: true
    inactive: true