# SearXNG settings

use_default_settings:
  engines:
    remove:
      - radio browser
      - ahmia
      - torch
      - yacy images

general:
  debug: false
  instance_name: "SearXNG"

search:
  safe_search: 0
  formats:
    - json

outgoing:
  request_timeout: 12.0

server:
  secret_key: "dummy"
  port: 55510
  limiter: false
  image_proxy: false

ui:
  static_use_hash: true

enabled_plugins:
  - 'Hash plugin'
  - 'Self Informations'
  - 'Tracker URL remover'

# Engines (Explicitly Defined)
engines:
  - name: google
    engine: google
    disabled: false
  - name: bing
    engine: bing
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    disabled: false
  - name: wikidata
    engine: wikidata
    disabled: false