# SearXNG settings
use_default_settings: false

general:
  debug: false
  instance_name: "SearXNG"

search:
  safe_search: 0
  formats:
    - json

outgoing:
  request_timeout: 12.0

server:
  secret_key: "dummy"
  port: 55510
  limiter: false
  image_proxy: false

ui:
  static_use_hash: true

enabled_plugins:
  - 'Hash plugin'
  - 'Self Informations'
  - 'Tracker URL remover'
  - 'Ahmia blacklist'

# Engines (Explicitly Defined)
engines:

  # ---- Google ----
  - name: google
    engine: google
    timeout: 6.0
    disabled: false

  # ---- Bing ----
  - name: bing
    engine: bing
    timeout: 6.0
    disabled: false

  # ---- DuckDuckGo ----
  - name: duckduckgo
    engine: duckduckgo
    timeout: 6.0
    disabled: false

  # ---- WikiData ----
  - name: wikidata
    engine: wikidata
    timeout: 6.0
    disabled: false